---
search: false
format:
  pdf:
    documentclass: resume
    keep-tex: false
    mainfont: TeX Gyre Pagella
    include-in-header:
      - text: |
          \usepackage[left=0.75in,top=0.6in,right=0.75in,bottom=0.75in]{geometry}
          \usepackage{atenddvi}
          \usepackage{hyperref}
          \usepackage{enumitem}
          \usepackage{lastpage}
          \usepackage{fancyhdr}
          \pagestyle{fancy}
          \fancyhf{}
          \fancyfoot[C]{\thepage/\pageref*{LastPage}}
          \renewcommand{\headrulewidth}{0pt}
          \renewcommand{\footrulewidth}{0pt}
          \setlength{\footskip}{30pt}
          \newcommand{\tab}[1]{\hspace{.2667\textwidth}\rlap{#1}}
          \newcommand{\itab}[1]{\hspace{0em}\rlap{#1}}
          \makeatletter
          \renewcommand{\printname}{%
            \begingroup
              \hfil{\namesize\bf \@name}\hfil
              \nameskip\break
            \endgroup
          }
          \makeatother
          \name{Sunwoo Kwak}
          \address{\href{https://scholar.google.com/citations?user=c22rzSYAAAAJ&hl=en}{Google Scholar} / \href{https://sunwookwak-polisci.github.io/}{Website}}
          \address{\href{mailto:sunwookwak@gmail.com}{sunwookwak@gmail.com}}
---

\begin{center}
(Updated: September 17, 2026)
\end{center}

```{=latex}
\begin{rSection}{Education}

\newcommand{\edudetail}[2]{%
  \par\vspace{0.12em}%
  \noindent\hspace{1em}%
  \begin{minipage}[t]{\dimexpr\linewidth-1em-4.5em\relax}
    \settowidth{\dimen0}{\textit{#1: }}%
    \hangindent=\dimen0\hangafter=1\raggedright
    \textit{#1: }#2
  \end{minipage}\par
}

\textbf{Incoming Ph.D.\ Student, Department of Politics, Princeton University} \hfill \textit{beginning September 2027}

\vspace{0.45em}

\textbf{M.A., Department of Political Science, Yonsei University} \hfill \textit{2026}
\edudetail{Thesis}{``Ideological Primary Challenges and Bipartisan Cosponsorship in the U.S.\ House: Strategic Retreat Among Challenged Incumbents''}

\vspace{0.45em}

\textbf{B.A., Underwood International College, Yonsei University} \hfill \textit{2025}
\edudetail{Major}{Political Science and International Relations}

\end{rSection}
```


```{=latex}
\begin{rSection}{RESEARCH INTERESTS}
```

American Politics · Legislative Politics (Congress) · Elections · Public Opinion · Korean Politics



```{=latex}
\end{rSection}
```

```{=latex}
\begin{rSection}{PUBLICATIONS}
```

1. Kang, Sinjae, **Sunwoo Kwak**, and Eunmi Cho. 2026. "A Cosponsorship Network Analysis of Life and Safety Legislation Before and After the Sewol Ferry Disaster: Evidence from the 17th--22nd National Assemblies of Korea." *Dispute Resolution Studies Review*, 24(2): 123--162. [in Korean]

2. **Kwak, Sunwoo**, Eunmi Cho, and Sinjae Kang. 2026. "Who Controls the Legislative Process? Party Cartels, Committee Gatekeepers, and Subcommittee Activity in the South Korean National Assembly." *Legislative Studies Quarterly*, 51(2): e70072.

3. Kang, Sinjae, **Sunwoo Kwak**, and Jeongmin Lee. 2025. "Did the 2019 Revision of the National Assembly Act Revitalize Subcommittees? Analyzing the Frequency and Scheduling Determinants of Bill Review Subcommittee Meetings." *Legislation and Policy Studies*, 17(1): 5--36. [in Korean]

4. Terashita, Kazuhiro, Eunmi Cho, Juhyeon Jeong, and **Sunwoo Kwak**. 2024. "Who Mentions the Region?: Analyzing Geographical Representation through Parliamentary Speeches." *Journal of Parliamentary Research*, 19(2): 5--42. [in Korean]

```{=latex}
\end{rSection}


\begin{rSection}{WORKING PAPERS}
```
"Who are the People? A Computational History of Democracy" (with Hyeongjae Lee, Seonwoo Ahn, Jisung Yoon, June Jeon, and Taegyoon Kim)

"Economic Agendas in Governors' Speeches Using Text as Data: Impact of Electoral and Institutional Conditions" (with Eunmi Cho)

"Mentioning Party Labels in Campaign Ads: Changing Campaign Behavior under a Polarized and Nationalized Context" (with Kyungrim Chung and Yoojin Kim)

```{=latex}
\end{rSection}

\begin{rSection}{CONFERENCE PRESENTATIONS}
```

American Political Science Association (APSA) Annual Meeting \hfill \textit{2025}

Midwest Political Science Association (MPSA) Annual Conference \hfill \textit{2025}

International Political Science Association (IPSA) World Congress \hfill \textit{2025}

International Studies Association (ISA) Annual Convention \hfill \textit{2025}

World Association for Public Opinion Research (WAPOR) Annual Conference \hfill \textit{2024}

World Association for Public Opinion Research (WAPOR) Asia Pacific Annual Conference \hfill \textit{2025}

Korean Political Science Association (KPSA) Annual Conference \hfill \textit{2023, 2024}

Korean Political Science Association (KPSA) Summer Conference \hfill \textit{2024, 2025}



```{=latex}
\end{rSection}

\begin{rSection}{AWARDS \& HONORS}
```

**Graduate**

- Best Paper Award, Yonsei University Graduate Student Association Academic Support Program (November 2025)
   - "Economic Agendas in Governors' Speeches Using Text as Data: Impact of Electoral and Institutional Conditions"


**Undergraduate**

- Highest Honors Scholarship (Spring 2023, Fall 2023, Spring 2024, Fall 2024)

```{=latex}
\end{rSection}

\begin{rSection}{TEACHING EXPERIENCE}
```

**Graduate Teaching Assistant** (Department of Political Science, Yonsei University)

- Applied Data Analysis (Spring 2025)
- Method of Empirical Research (Spring 2025)

```{=latex}
\end{rSection}

\begin{rSection}{RESEARCH EXPERIENCE}
```

**Lab Member** (Department of Political Science, Yonsei University)

- Applied Political Methodology Lab (Fall 2024--Spring 2026; Lab Manager: Fall 2025--Spring 2026)

- Qualities of Democracy Lab (Fall 2023--Spring 2026)

```{=latex}
\end{rSection}

\begin{rSection}{METHODS TRAINING}
```

**Workshop and Program Participation**

- "2025 Summer Institute in Computational Social Science in Korea (SICSS-Korea)" organized by KDI School of Public Policy and Management and KAIST.
- "2024 Summer Methods Workshop" organized by Korean Association of Party Studies (KAPS).


**Related Coursework**

- "Special Topics in Political Methodology" (Spring 2025)
- "Advanced Method of Empirical Research" (Fall 2024)
- "Research Methods in Political Science" (Fall 2024)
- "Applied Data Analysis" (Spring 2023)

```{=latex}
\end{rSection}

\begin{rSection}{COMPUTATIONAL SKILLS}
```
**R, Python, LaTeX, Quarto**

```{=latex}
\end{rSection}

\begin{rSection}{LANGUAGES}
```
**Korean** (Native), **English** (Fluent)

```{=latex}
\end{rSection}
```

